### ISSUE TITLE
Publish artefact for Scala.js 1.0.1

### ISSUE THREAD

**Issue by tindzk** [scala-js/scala-js-env-jsdom-nodejs#41]
At the moment, I am trying to implement Scala.js 1.0 support in Bloop ([pull request](https://github.com/scalacenter/bloop/pull/1234/files)) and found that there is no scala-js-env-jsdom-nodejs artefact with version 1.0.1, only 1.0.0. However, looking at the past releases, I believe that this library is supposed to be published for every minor Scala.js release. For the time being, I have hard-coded both `scalajs-js-envs` and `scalajs-env-jsdom-nodejs` to v1.0.0 which hopefully should work too.

**Comment by sjrd** [comment]
> However, looking at the past releases, I believe that this library is supposed to be published for every minor Scala.js release.

That was only during milestones and RCS. Not anymore. Since Scala.js 1.x remains backward binary compatible with 1.0.0, you can and should use version 1.0.0 of this library with any future Scala.js 1.x version.

We will not publish new versions of this library just for the sake of newer versions of Scala.js. That would be useless overhead.

**Comment by tindzk** [comment]
Thanks for clarifying. Does the same apply to `scalajs-js-envs`? I see it was published for 1.0.1.

**Comment by sjrd** [comment]
`scalajs-js-envs` is part of the core of Scala.js. So of course it gets published for every version of Scala.js core. But even then you *can* use scalajs-js-envs 1.0.0 with Scala.js 1.0.1 (or conversely). They're compatible.
